version: 2
updates:
- package-ecosystem: npm
  directory: "/"
  schedule:
    interval: weekly
    time: "10:00"
  open-pull-requests-limit: 10
  ignore:
  - dependency-name: rollup-plugin-node-resolve
    versions:
    - "> 4.2.4"
  - dependency-name: eslint-plugin-jest
    versions:
    - 24.1.5
    - 24.1.9
    - 24.3.1
    - 24.3.2
    - 24.3.4
    - 24.3.5
  - dependency-name: rollup
    versions:
    - 2.38.0
    - 2.38.3
    - 2.38.5
    - 2.39.0
    - 2.40.0
    - 2.41.2
    - 2.42.2
    - 2.43.1
    - 2.45.1
  - dependency-name: postcss
    versions:
    - 8.2.10
    - 8.2.5
    - 8.2.6
    - 8.2.7
    - 8.2.8
  - dependency-name: eslint
    versions:
    - 7.19.0
    - 7.20.0
    - 7.21.0
    - 7.22.0
    - 7.23.0
    - 7.24.0
  - dependency-name: "@rollup/plugin-commonjs"
    versions:
    - 17.1.0
    - 18.0.0
  - dependency-name: "@rollup/plugin-node-resolve"
    versions:
    - 11.1.1
    - 11.2.0
    - 11.2.1
  - dependency-name: uswds
    versions:
    - 2.10.1
    - 2.10.2
    - 2.11.1
  - dependency-name: autoprefixer
    versions:
    - 10.2.4
    - 10.2.5
  - dependency-name: stylelint
    versions:
    - 13.10.0
    - 13.11.0
    - 13.12.0
  - dependency-name: nunjucks
    versions:
    - 3.2.3
  - dependency-name: sass
    versions:
    - 1.32.6
    - 1.32.7
    - 1.32.8
  - dependency-name: stylelint-scss
    versions:
    - 3.19.0
